name: Selenium Tests + Slack Report

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 6PM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium Tests and Generate Report
      run: |
        pytest testcases/test_billing_dashboard.py --html=report.html --self-contained-html

    - name: Upload HTML report artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: selenium-report
        path: report.html

    - name: Upload report to Slack
      run: |
        curl -F file=@report.html \
             -F "initial_comment=Selenium Test Report for $(date)" \
             -F channels=hml_automation \
             -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
             https://slack.com/api/files.upload
