name: Selenium Tests + Slack Report

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 6PM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium Tests and Generate Report
      run: |
        pytest testcases/test_billing_dashboard.py --html=report.html --self-contained-html

    - name: Upload HTML report artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: selenium-report
        path: report.html

    - name: Move report.html into report/index.html
      run: |
        mkdir -p report
        mv report.html report/index.html

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./report

    - name: Notify Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      run: |
        curl -X POST https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
                "channel": "hml_automation",
                "text": "✅ Selenium Test Report: https://Shubhomjoshi.github.io/hml/report/report.html"
              }'