name: Run Selenium Tests and Deploy Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest and Generate HTML Report
      run: |
        pytest testcases/test_billing_dashboard.py \
               --html=report.html \
               --self-contained-html

    - name: Move report.html into report/index.html for GitHub Pages
      run: |
        mkdir -p report
        mv report.html report/index.html

    - name: Deploy report folder to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./report
